IF OBJECT_ID( 'TEMPDB.DBO.#Temp' ) IS NOT NULL
	BEGIN
		DROP TABLE #Temp
	END;

CREATE TABLE #Temp (
 [ID]	INT IDENTITY
,[Text]	VARCHAR(MAX)
);

INSERT INTO #Temp VALUES 

 ( '0253U'  )
,( 'Reproductive medicine (endometrial receptivity analysis), RNA gene expression profile, 238 genes by next-generation sequencing, endometrial tissue, predictive algorithm reported as endometrial window of implantation (e.g., pre-receptive, receptive, post-receptive)'  )
,( '0568T'  )
,( 'Introduction of mixture of saline and air for sonosalpingography to confirm occlusion of fallopian tubes, transcervical approach, including transvaginal ultrasound and pelvic ultrasound'  )
,( '52402'  )
,( 'Cystourethroscopy with transurethral resection or incision of ejaculatory ducts'  )
,( '54500'  )
,( 'Biopsy of testis, needle (separate procedure)'  )
,( '54505'  )
,( 'Biopsy of testis, incisional (separate procedure)'  )
,( '55300'  )
,( 'Vasotomy for vasograms, seminal vesiculograms, or epididymograms, unilateral or bilateral'  )
,( '55530'  )
,( 'Excision of varicocele or ligation of spermatic veins for varicocele; (separate procedure)'  )
,( '55535'  )
,( 'Excision of varicocele or ligation of spermatic veins for varicocele; abdominal approach'  )
,( '55550'  )
,( 'Laparoscopy, surgical, with ligation of spermatic veins for varicocele'  )
,( '55870'  )
,( 'Electroejaculation'  )
,( '58140'  )
,( 'Myomectomy, excision of fibroid tumor(s) of uterus, 1 to 4 intramural myoma(s) with total weight of 250 g or less and/or removal of surface myomas; abdominal approach'  )
,( '58145'  )
,( 'Myomectomy, excision of fibroid tumor(s) of uterus, 1 to 4 intramural myoma(s) with total weight of 250 g or less and/or removal of surface myomas; vaginal approach'  )
,( '58146'  )
,( 'Myomectomy, excision of fibroid tumor(s) of uterus, 5 or more intramural myomas and/or intramural myomas with total weight greater than 250 g, abdominal approach'  )
,( '58321'  )
,( 'Artificial insemination; intra-cervical'  )
,( '58322'  )
,( 'Artificial insemination; intra-uterine'  )
,( '58323'  )
,( 'Sperm washing for artificial insemination'  )
,( '58340'  )
,( 'Catheterization and introduction of saline or contrast material for saline infusion sonohysterography (SIS) or hysterosalpingography'  )
,( '58345'  )
,( 'Transcervical introduction of fallopian tube catheter for diagnosis and/or re-establishing patency (any method), with or without hysterosalpingography'  )
,( '58350'  )
,( 'Chromotubation of oviduct, including materials'  )
,( '58545'  )
,( 'Laparoscopy, surgical, myomectomy, excision; 1 to 4 intramural myomas with total weight of 250 g or less and/or removal of surface myomas'  )
,( '58546'  )
,( 'Laparoscopy, surgical, myomectomy, excision; 5 or more intramural myomas and/or intramural myomas with total weight greater than 250 g'  )
,( '58555'  )
,( 'Hysteroscopy, diagnostic (separate procedure)'  )
,( '58559'  )
,( 'Hysteroscopy, surgical; with lysis of intrauterine adhesions (any method)'  )
,( '58660'  )
,( 'Laparoscopy, surgical; with lysis of adhesions (salpingolysis, ovariolysis) (separate procedure)'  )
,( '58662'  )
,( 'Laparoscopy, surgical; with fulguration or excision of lesions of the ovary, pelvic viscera, or peritoneal surface by any method'  )
,( '58670'  )
,( 'Laparoscopy, surgical; with fulguration of oviducts (with or without transection)'  )
,( '58672'  )
,( 'Laparoscopy, surgical; with fimbrioplasty'  )
,( '58673'  )
,( 'Laparoscopy, surgical; with salpingostomy (salpingoneostomy)'  )
,( '58740'  )
,( 'Lysis of adhesions (salpingolysis, ovariolysis)'  )
,( '58752'  )
,( 'Tubouterine implantation'  )
,( '58760'  )
,( 'Fimbrioplasty'  )
,( '58770'  )
,( 'Salpingostomy (salpingoneostomy)'  )
,( '58800'  )
,( 'Drainage of ovarian cyst(s), unilateral or bilateral (separate procedure); vaginal approach'  )
,( '58805'  )
,( 'Drainage of ovarian cyst(s), unilateral or bilateral (separate procedure); abdominal approach'  )
,( '58920'  )
,( 'Wedge resection or bisection of ovary, unilateral or bilateral'  )
,( '58970'  )
,( 'Follicle puncture for oocyte retrieval, any method'  )
,( '58974'  )
,( 'Embryo transfer, intrauterine'  )
,( '58976'  )
,( 'Gamete, zygote, or embryo intrafallopian transfer, any method'  )
,( '74440'  )
,( 'Vasography, vesiculography, or epididymography, radiological supervision and interpretation'  )
,( '74740'  )
,( 'Hysterosalpingography, radiological supervision and interpretation'  )
,( '74742'  )
,( 'Transcervical catheterization of fallopian tube, radiological supervision and interpretation'  )
,( '76830'  )
,( 'Ultrasound, transvaginal'  )
,( '76831'  )
,( 'Saline infusion sonohysterography (SIS), including color flow Doppler, when performed'  )
,( '76856'  )
,( 'Ultrasound, pelvic (nonobstetric), real time with image documentation; complete'  )
,( '76857'  )
,( 'Ultrasound, pelvic (nonobstetric), real time with image documentation; limited or follow-up (e.g., for follicles)'  )
,( '76870'  )
,( 'Ultrasound, scrotum and contents'  )
,( '76872'  )
,( 'Ultrasound, transrectal'  )
,( '76948'  )
,( 'Ultrasonic guidance for aspiration of ova, imaging supervision and interpretation'  )
,( '80415'  )
,( 'Chorionic gonadotropin stimulation panel; estradiol response This panel must include the following: Estradiol, total (82670 x 2 on 3 pooled blood samples)'  )
,( '80426'  )
,( 'Gonadotropin releasing hormone stimulation panel This panel must include the following: Follicle stimulating hormone (FSH) (83001 x 4) Luteinizing hormone (LH) (83002 x 4)'  )
,( '81224'  )
,( 'CFTR (cystic fibrosis transmembrane conductance regulator) (e.g., cystic fibrosis) gene analysis; intron 8 poly-T analysis (e.g., male infertility)'  )
,( '82397'  )
,( 'Chemiluminescent assay'  )
,( '82670'  )
,( 'Estradiol; total'  )
,( '83001'  )
,( 'Gonadotropin; follicle stimulating hormone (FSH)'  )
,( '83002'  )
,( 'Gonadotropin; luteinizing hormone (LH)'  )
,( '83498'  )
,( 'Hydroxyprogesterone, 17-d'  )
,( '83520'  )
,( 'Immunoassay for analyte other than infectious agent antibody or infectious agent antigen; quantitative, not otherwise specified'  )
,( '84144'  )
,( 'Progesterone'  )
,( '84146'  )
,( 'Prolactin'  )
,( '84402'  )
,( 'Testosterone; free'  )
,( '84403'  )
,( 'Testosterone; total'  )
,( '84443'  )
,( 'Thyroid stimulating hormone (TSH)'  )
,( '84830'  )
,( 'Ovulation tests, by visual color comparison methods for human luteinizing hormone'  )
,( '88182'  )
,( 'Flow cytometry, cell cycle or DNA analysis'  )
,( '88248'  )
,( 'Chromosome analysis for breakage syndromes; baseline breakage, score 50-100 cells, count 20 cells, 2 karyotypes (e.g., for ataxia telangiectasia, Fanconi anemia, fragile X)'  )
,( '88261'  )
,( 'Chromosome analysis; count 5 cells, 1 karyotype, with banding'  )
,( '88262'  )
,( 'Chromosome analysis; count 15-20 cells, 2 karyotypes, with banding'  )
,( '88263'  )
,( 'Chromosome analysis; count 45 cells for mosaicism, 2 karyotypes, with banding'  )
,( '88273'  )
,( 'Molecular cytogenetics; chromosomal in situ hybridization, analyze 10-30 cells (e.g., for microdeletions)'  )
,( '88280'  )
,( 'Chromosome analysis; additional karyotypes, each study'  )
,( '88283'  )
,( 'Chromosome analysis; additional specialized banding technique (e.g., NOR, C-banding)'  )
,( '88285'  )
,( 'Chromosome analysis; additional cells counted, each study'  )
,( '89250'  )
,( 'Culture of oocyte(s)/embryo(s), less than 4 days'  )
,( '89251'  )
,( 'Culture of oocyte(s)/embryo(s), less than 4 days; with co-culture of oocyte(s)/embryos'  )
,( '89253'  )
,( 'Assisted embryo hatching, microtechniques (any method)'  )
,( '89254'  )
,( 'Oocyte identification from follicular fluid'  )
,( '89255'  )
,( 'Preparation of embryo for transfer (any method)'  )
,( '89257'  )
,( 'Sperm identification from aspiration (other than seminal fluid)'  )
,( '89258'  )
,( 'Cryopreservation; embryo(s)'  )
,( '89259'  )
,( 'Cryopreservation; sperm'  )
,( '89260'  )
,( 'Sperm isolation; simple prep (e.g., sperm wash and swim-up) for insemination or diagnosis with semen analysis'  )
,( '89261'  )
,( 'Sperm isolation; complex prep (e.g., Percoll gradient, albumin gradient) for insemination or diagnosis with semen analysis'  )
,( '89264'  )
,( 'Sperm identification from testis tissue, fresh or cryopreserved'  )
,( '89268'  )
,( 'Insemination of oocytes'  )
,( '89272'  )
,( 'Extended culture of oocyte(s)/embryo(s), 4-7 days'  )
,( '89280'  )
,( 'Assisted oocyte fertilization, microtechnique; less than or equal to 10 oocytes'  )
,( '89281'  )
,( 'Assisted oocyte fertilization, microtechnique; greater than 10 oocytes'  )
,( '89290'  )
,( 'Biopsy, oocyte polar body or embryo blastomere, microtechnique (for pre-implantation genetic diagnosis); less than or equal to 5 embryos'  )
,( '89291'  )
,( 'Biopsy, oocyte polar body or embryo blastomere, microtechnique (for pre-implantation genetic diagnosis); greater than 5 embryos'  )
,( '89300'  )
,( 'Semen analysis; presence and/or motility of sperm including Huhner test (post coital)'  )
,( '89310'  )
,( 'Semen analysis; motility and count (not including Huhner test)'  )
,( '89320'  )
,( 'Semen analysis; volume, count, motility, and differential'  )
,( '89321'  )
,( 'Semen analysis; sperm presence and motility of sperm, if performed'  )
,( '89322'  )
,( 'Semen analysis; volume, count, motility, and differential using strict morphologic criteria (e.g., Kruger)'  )
,( '89325'  )
,( 'Sperm antibodies'  )
,( '89329'  )
,( 'Sperm evaluation; hamster penetration test'  )
,( '89330'  )
,( 'Sperm evaluation; cervical mucus penetration test, with or without spinnbarkeit test'  )
,( '89331'  )
,( 'Sperm evaluation, for retrograde ejaculation, urine (sperm concentration, motility, and morphology, as indicated)'  )
,( '89335'  )
,( 'Cryopreservation, reproductive tissue, testicular'  )
,( '89337'  )
,( 'Cryopreservation, mature oocyte(s)'  )
,( '89342'  )
,( 'Storage (per year); embryo(s)'  )
,( '89343'  )
,( 'Storage (per year); sperm/semen'  )
,( '89344'  )
,( 'Storage (per year); reproductive tissue, testicular/ovarian'  )
,( '89346'  )
,( 'Storage (per year); oocyte(s)'  )
,( '89352'  )
,( 'Thawing of cryopreserved; embryo(s)'  )
,( '89353'  )
,( 'Thawing of cryopreserved; sperm/semen, each aliquot'  )
,( '89354'  )
,( 'Thawing of cryopreserved; reproductive tissue, testicular/ovarian'  )
,( '89356'  )
,( 'Thawing of cryopreserved; oocytes, each aliquot'  )
,( '89398'  )
,( 'Unlisted reproductive medicine laboratory procedure [when used for cryopreservation of ovarian tissue or hyaluronan binding assay]'  )
,( 'J0725'  )
,( 'Injection, chorionic gonadotropin, per 1,000 USP units'  )
,( 'J3355'  )
,( 'Injection, urofollitropin, 75 IU'  )
,( 'S0122'  )
,( 'Injection, menotropins, 75 IU'  )
,( 'S0126'  )
,( 'Injection, follitropin alfa, 75 IU'  )
,( 'S0128'  )
,( 'Injection, follitropin beta, 75 IU'  )
,( 'S0132'  )
,( 'Injection, ganirelix acetate, 250 mcg'  )
,( 'S3655'  )
,( 'Antisperm antibodies test (immunobead)'  )
,( 'S4011'  )
,( 'In vitro fertilization; including but not limited to identification and incubation of mature oocytes, fertilization with sperm, incubation of embryo(s), and subsequent visualization for determination of development'  )
,( 'S4013'  )
,( 'Complete cycle, gamete intrafallopian transfer (GIFT), case rate'  )
,( 'S4014'  )
,( 'Complete cycle, zygote intrafallopian transfer (ZIFT), case rate'  )
,( 'S4015'  )
,( 'Complete in vitro fertilization cycle, not otherwise specified, case rate'  )
,( 'S4016'  )
,( 'Frozen in vitro fertilization cycle, case rate'  )
,( 'S4017'  )
,( 'Incomplete cycle, treatment cancelled prior to stimulation, case rate'  )
,( 'S4018'  )
,( 'Frozen embryo transfer procedure cancelled before transfer, case rate'  )
,( 'S4020'  )
,( 'In vitro fertilization procedure cancelled before aspiration, case rate'  )
,( 'S4021'  )
,( 'In vitro fertilization procedure cancelled after aspiration, case rate'  )
,( 'S4022'  )
,( 'Assisted oocyte fertilization, case rate'  )
,( 'S4023'  )
,( 'Donor egg cycle, incomplete, case rate'  )
,( 'S4025'  )
,( 'Donor services for in vitro fertilization (sperm or embryo), case rate'  )
,( 'S4026'  )
,( 'Procurement of donor sperm from sperm bank'  )
,( 'S4027'  )
,( 'Storage of previously frozen embryos'  )
,( 'S4028'  )
,( 'Microsurgical epididymal sperm aspiration (MESA)'  )
,( 'S4030'  )
,( 'Sperm procurement and cryopreservation services; initial visit'  )
,( 'S4031'  )
,( 'Sperm procurement and cryopreservation services; subsequent visit'  )
,( 'S4035'  )
,( 'Stimulated intrauterine insemination (IUI), case rate'  )
,( 'S4037'  )
,( 'Cryopreserved embryo transfer, case rate'  )
,( 'S4040'  )
,( 'Monitoring and storage of cryopreserved embryos, per 30 days' );

/**************************************************************************************************************/

ALTER TABLE #Temp
ADD [Column Type] INT;

UPDATE #Temp
SET [Column Type] =
	[ID] % 2

ALTER TABLE #Temp
ADD [Row Number] INT;

UPDATE #Temp
SET [Row Number] =
	ROUND( [ID] / 2.0, 0 )

/**************************************************************************************************************/

/*

SELECT
*
FROM
#Temp

*/

/**************************************************************************************************************/


SELECT
 [Code] =
	[1]
,[Description] =
	[0]
FROM
( SELECT [Row Number], [Text], [Column Type] FROM #Temp ) AS Base
PIVOT
(
MAX( [Text] )
FOR
[Column Type] IN ( [0], [1] )
) AS PivotedTable