USE JMarx;
GO

IF OBJECT_ID( 'JMarx.SUPPORT.EMERGENCY_ROOM_CODES' ) IS NOT NULL
	BEGIN
		DROP PROCEDURE SUPPORT.EMERGENCY_ROOM_CODES 
	END;
GO

CREATE PROCEDURE SUPPORT.EMERGENCY_ROOM_CODES AS
BEGIN

DECLARE @ReturnTable [CATEGORY_AND_CODE_TABLE_TYPE];

INSERT INTO @ReturnTable DEFAULT VALUES;

UPDATE @ReturnTable
SET
 [REVENUE_CODE]	= '0450,0451,0452,0459,0981';

SELECT
*
FROM
@ReturnTable

END

/* EXECUTE PROCEDURE */
--EXEC SUPPORT.EMERGENCY_ROOM_CODES


/* EXAMPLE OF HOW TO USE PROCEDURE */
/*

DECLARE
 @ERRevenueCodes AS VARCHAR(255)
,@ERRevQuery	AS VARCHAR(255)
,@ReturnTable [SUPPORT].[CATEGORY_AND_CODE_TABLE_TYPE];

INSERT INTO @ReturnTable
EXEC SUPPORT.EMERGENCY_ROOM_CODES

SET @ERRevenueCodes = ( SELECT [Revenue_code] FROM @ReturnTable )

SET @ERRevQuery = CONCAT( '

SELECT * FROM WEA_EDW.DIM.SERVICE_DIM 
WHERE
SERVICE_DIM.STANDARDIZED_SERVICE_CODE IN ( ', @ERRevenueCodes,' )
AND
WEA_EDW.DIM.SERVICE_DIM.SERVICE_TYPE_NAME = ''UB Revenue Code''
');

EXEC ( @ERRevQuery )

*/
