SELECT
 [Date] =
	CAST( DateDim.DATE_VALUE AS DATE )
,[Account Type] =
	AccountType.ACCOUNT_TYPE_NAME
,[Account Name] =
	TopAccount.ACCOUNT_NAME
,[Company Name] =
	ISNULL( PRODUCT.SUB_COMPANY_NAME, 'WEA Trust' )
,[Line of Business] =
	BPTC.BENEFIT_PLAN_TYPE_NAME
,[Member Months] =
	COUNT( DISTINCT MHF.MEMBER_HCC_ID )

FROM 
[wea_prod_dw].[dbo].[DATE_DIMENSION] AS DateDim

	LEFT JOIN [wea_prod_dw].[dbo].[ACCOUNT_HISTORY_FACT] AS AHF
		ON DateDim.DATE_KEY BETWEEN AHF.VERSION_EFF_DATE_KEY AND AHF.VERSION_EXP_DATE_KEY - 1

		LEFT JOIN [wea_prod_dw].[dbo].[ACCOUNT_HISTORY_FACT] AS TopAccount
			ON TopAccount.ACCOUNT_KEY = AHF.TOP_ACCOUNT_KEY
			AND DateDim.DATE_KEY BETWEEN TopAccount.VERSION_EFF_DATE_KEY AND TopAccount.VERSION_EXP_DATE_KEY - 1

			LEFT JOIN wea_prod_dw.dbo.ACCOUNT_TYPE_CODE AS AccountType
				ON AccountType.ACCOUNT_TYPE_KEY = TopAccount.ACCOUNT_TYPE_KEY

		LEFT JOIN [wea_prod_dw].[dbo].[MEMBER_HISTORY_FACT] AS MHF
			ON MHF.ACCOUNT_KEY = AHF.ACCOUNT_KEY
			AND DateDim.DATE_KEY BETWEEN MHF.VERSION_EFF_DATE_KEY AND MHF.VERSION_EXP_DATE_KEY - 1

			LEFT JOIN [wea_prod_dw].[dbo].[MEMBER_HIST_FACT_TO_BNFT_PLAN] AS MHFToBP
				ON MHFToBP.MEMBER_HISTORY_FACT_KEY = MHF.MEMBER_HISTORY_FACT_KEY

				LEFT JOIN [wea_prod_dw].[dbo].[BENEFIT_PLAN_HISTORY_FACT] AS BPHF
					ON BPHF.BENEFIT_PLAN_KEY = MHFToBP.BENEFIT_PLAN_KEY
					AND DateDim.DATE_KEY BETWEEN BPHF.VERSION_EFF_DATE_KEY AND BPHF.VERSION_EXP_DATE_KEY - 1

					LEFT JOIN wea_prod_dw.dbo.PRODUCT AS PRODUCT
						ON PRODUCT.PRODUCT_KEY = BPHF.BENEFIT_PLAN_PRODUCT_KEY

						LEFT JOIN [wea_prod_dw].[dbo].[BENEFIT_PLAN_TYPE_CODE] AS BPTC
							ON BPTC.BENEFIT_PLAN_TYPE_KEY = PRODUCT.BENEFIT_PLAN_TYPE_KEY

WHERE 
DAY_OF_MONTH = '15'
AND
YEAR_NUMBER BETWEEN CASE WHEN ( YEAR( GETDATE() ) - 5 ) >= 2013 THEN ( YEAR( GETDATE() ) - 5 )
						 ELSE 2013
						 END
						 AND YEAR( GETDATE() )
AND
YEAR_NUMBER > 2013 /* 2013 has partial data  */
AND
BENEFIT_PLAN_STATUS = 'a' /* Active Plans Only*/
AND
MHF.MEMBER_STATUS = 'a' /* Active Members Only */
AND
AHF.ACCOUNT_STATUS = 'a' /* Active Accounts Only */
AND
BPTC.BENEFIT_PLAN_TYPE_NAME IN ( 'Medical', 'Pharmacy' )
GROUP BY
 CAST( DateDim.DATE_VALUE AS DATE )
,AccountType.ACCOUNT_TYPE_NAME
,ISNULL( PRODUCT.SUB_COMPANY_NAME, 'WEA Trust' )
,TopAccount.ACCOUNT_NAME
,BPTC.BENEFIT_PLAN_TYPE_NAME
ORDER BY
[Date] DESC
